# Generated by Django 5.1.6 on 2025-03-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CorrectAnswer',
        ),
    ]
