# Generated by Django 5.1.6 on 2025-03-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='users_customuser',
        ),
    ]
