# Generated by Django 5.1.6 on 2025-03-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='num_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
    ]
