# Generated by Django 5.1.6 on 2025-03-03 12:20

import classrooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(default=classrooms.models.generate_unique_code, max_length=10, unique=True),
        ),
    ]
